### PR TITLE
Add MacAddress generator

### PR DESCRIPTION
**Pull request by ustrajunior**

### CODE REVIEW

**Comment by Pallinder** [comment]
Good stuff! Would love some tests before merge.

**Comment by ustrajunior** [comment]
Sure. I will write the tests and send the request again.

**Comment by ustrajunior** [comment]
Hey @Pallinder, I added the tests. It's ok?

**Comment by ustrajunior** [comment]
Hey, @Pallinder any news about the request? Thanks.

**Comment by Pallinder** [comment]
Good to go. Thanks!

**Pull request merged**
