### PR TITLE
Randomness Improvements

### PR DESCRIPTION
**Pull request by ericfialkowski**
On windows I wasn't getting new data whenever I called any methods (such as SillyName().) I created a private instance of rand that is seeded based on current time and that fixed the behavior I was seeing. Additionally, I added some more paragraphs since I was getting many duplicates in my testing due to the low number of options.

### CODE REVIEW

**Comment by Pallinder** [comment]
Perhaps we can combine this PR with #39 so that people can supply their own seed, what do you think?

**Comment by ericfialkowski** [comment]
I think that makes sense. I'm not sure that PR is compatible with mine but I could make changes that would provide equivalent functionality.

**Comment by ericfialkowski** [comment]
So I inadvertently included another change that I wasn't intending to push out yet (e38a116). However, dec169d has the ability to provide a custom rand object which I believe will satisfy the intent of PR 39.

**Comment by Pallinder** [comment]
@ericfialkowski Yeah, that is most likely the way to go.

**Comment by ericfialkowski** [comment]
I reverted the extraneous change I hadn't intended on including.

**Comment by Pallinder** [comment]
Great.

First of all, do you mind running gofmt so we can the same formatting?
And second of all, what do you think about renaming the r variable to something more descriptive?

**Comment by ericfialkowski** [comment]
ran gofmt on the project and renamed "r" to "privateRand"

**Comment by Pallinder** [comment]
Sorry about being a bit slow, was away on some business. I'll check the PR

**Comment by Pallinder** [comment]
Thanks!

**Pull request merged**
