### PR TITLE
Support for Country localised street names and provinces, currently supporting GB (Great Britain)

### PR DESCRIPTION
**Pull request by MarkSonghurst**
Background
This change enables support for Country localised street names and provinces.

Caveats 
The change only supports Great Britain (GB) and US at the moment. Other countries can be added easily enough.

Changes 
* Constant JSON data added for GB provinces and street names.
* Function ProvinceForCountry added
* Function StreetForCountry added
* Test cases added.

Checklist
- [x] Tests
- [x] Documentation
- [x] Gofmt run on your code

### CODE REVIEW

**Comment by Pallinder** [comment]
Great, thanks for this!
Could you update your PR description to be inline with the template that we've added. 
Once that's done I'll merge this and include it in the 1.1.0 release that is coming up now.

**Comment by MarkSonghurst** [comment]
@Pallinder I cannot see a template you have added? More clues required.

**Comment by Pallinder** [comment]
@MarkSonghurst https://github.com/Pallinder/go-randomdata/blob/master/.github/PULL_REQUEST_TEMPLATE.md look at that one

**Comment by MarkSonghurst** [comment]
@Pallinder OK, thanks.
And to be specific, where is the PR Description I should be editing? You mean the first comment in this thread, or the title of the PR, or something else?

**Comment by MarkSonghurst** [comment]
@Pallinder Done.

**Pull request merged**
